spring:
  freemarker:
    enabled: true
    template-loader-path: classpath:/templates/freemarker/
    suffix: .ftl
    check-template-location: false
server:
  port: 60003
  error:
    whitelabel:
      enabled: false
logging:
  config: file:config/log4j2.xml
