package org.endless.ddd.simplified.generator.common;

/**
 * ProjectConstants
 * <p>
 * 项目常量
 * <p>
 * DDD通用层 - Project领域
 * <p>
 * create 2025/07/29 16:00
 * <p>
 * update 2025/07/29 16:00
 *
 * @author Deng Haozhi
 * @since 1.0.0
 */
public final class ProjectConstants {

    private ProjectConstants() {
        // 私有构造函数，防止实例化
    }

    /**
     * 项目状态常量
     */
    public static final class Status {

        public static final String DRAFT = "DRAFT";

        public static final String ACTIVE = "ACTIVE";

        public static final String INACTIVE = "INACTIVE";

        public static final String ARCHIVED = "ARCHIVED";

        public static final String DELETED = "DELETED";
    }

    /**
     * 项目类型常量
     */
    public static final class Type {

        public static final String MICROSERVICE = "MICROSERVICE";

        public static final String MONOLITH = "MONOLITH";

        public static final String API_GATEWAY = "API_GATEWAY";

        public static final String EVENT_DRIVEN = "EVENT_DRIVEN";

        public static final String CQRS = "CQRS";
    }

    /**
     * 默认值常量
     */
    public static final class Defaults {

        public static final String DEFAULT_VERSION = "1.0.0";

        public static final String DEFAULT_AUTHOR = "System";

        public static final String DEFAULT_DESCRIPTION = "Generated by DDD Generator";

        public static final String DEFAULT_BASE_PACKAGE = "org.endless";

        public static final String DEFAULT_OUTPUT_PATH = "./generated";

        public static final String DEFAULT_ROOT_PATH = "/api";

        public static final String DEFAULT_SERVICE_SUB_PACKAGE = "service";
    }

    /**
     * 错误消息常量
     */
    public static final class ErrorMessages {

        public static final String PROJECT_ID_REQUIRED = "项目ID不能为空";

        public static final String PROJECT_NAME_REQUIRED = "项目名称不能为空";

        public static final String GROUP_ID_REQUIRED = "组ID不能为空";

        public static final String VERSION_REQUIRED = "版本不能为空";

        public static final String AUTHOR_REQUIRED = "作者不能为空";

        public static final String DESCRIPTION_REQUIRED = "描述不能为空";

        public static final String BASE_PACKAGE_REQUIRED = "基础包名不能为空";

        public static final String OUTPUT_PATH_REQUIRED = "输出路径不能为空";

        public static final String ROOT_PATH_REQUIRED = "根路径不能为空";

        public static final String SERVICE_SUB_PACKAGE_REQUIRED = "服务业务子包不能为空";

        public static final String DATABASE_TYPE_REQUIRED = "数据库类型不能为空";
    }

    /**
     * 成功消息常量
     */
    public static final class SuccessMessages {

        public static final String PROJECT_CREATED = "项目创建成功";

        public static final String PROJECT_UPDATED = "项目更新成功";

        public static final String PROJECT_DELETED = "项目删除成功";

        public static final String PROJECT_VALIDATED = "项目验证成功";

        public static final String CODE_GENERATED = "代码生成成功";
    }
}
